# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42cf8f17566d897e1d71a69ab3f4408de49d9ddddf8d2e4c5772fb984cf3fb859fe2e9c54eac08d9e0cda07ed32d6fd81638d3b4deeb774590c5b8514ca2fa94

test:
  secret_key_base: 4e1857efdb937e8e18debd4033e90f1579b212549e01982c0af8a96fc4071faf1014e6b2adfdca52313c21e6886e27fbe2ec776daf8126ead004c2125716b413

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
